# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [125]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [126]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [127]:
#your code here

**Check for data types**

In [128]:
#your code here

**Check for missing values**

In [129]:
#your code here

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [130]:
#your code here

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [131]:
#your code here

- Drop PassengerId and Name

In [132]:
#your code here

- For non-numerical columns, do dummies.

In [133]:
#your code here

**Perform Train Test Split**

In [134]:
#your code here

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [135]:
#your code here

- Evaluate your model's performance. Comment it

In [136]:
#your code here

---
# Solved LAB | Feature Engineering
---

| Variable      | Cat vs Num | Identity   | Original Python Type | Action | Convert to | Definition |
|---------------|------------|------------|----------------------|--------|------------|------------|
| PassengerId   | ID         | Identifier | object               | DROP   | —          | Unique ID for each passenger in the format gggg_pp (group and passenger number) |
| HomePlanet    | Cat        | Feature    | object               | ENCODE | int        | Planet the passenger departed from (Earth, Europa, Mars) |
| CryoSleep     | Cat (Bool) | Feature    | object               | ENCODE | int        | Whether the passenger was in cryosleep during the voyage (True/False) |
| Cabin         | Cat        | Feature    | object               | ENCODE | int        | Deck of the passenger’s cabin (first letter of original Cabin value: A–G, T) |
| Destination   | Cat        | Feature    | object               | ENCODE | int        | Planet the passenger will disembark to |
| Age           | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Age of the passenger in years |
| VIP           | Cat (Bool) | Feature    | object               | ENCODE | int        | Whether the passenger paid for VIP service (True/False) |
| RoomService   | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Amount billed for room service |
| FoodCourt     | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Amount billed at the food court |
| ShoppingMall  | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Amount billed at the shopping mall |
| Spa           | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Amount billed at the spa |
| VRDeck        | Num        | Feature    | float64              | IMPUTE + SCALE | float64 | Amount billed at the virtual reality deck |
| Name          | Cat        | Feature    | object               | DROP   | —          | Full name of the passenger |
| Transported   | Cat (Bool) | Target     | bool                 | TARGET | int        | Whether the passenger was transported to another dimension |

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [137]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [138]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [139]:
spaceship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

**Check the shape of your data**

In [140]:
# Check the shape of the dataset*
print("Dataset Shape:", spaceship.shape)
# number of rows 
print("Number of rows:", spaceship.shape[0])
# number of columns
print("Number of columns:", spaceship.shape[1])

Dataset Shape: (8693, 14)
Number of rows: 8693
Number of columns: 14

**Check for data types**

In [141]:
print("Data Types:")
display(spaceship.dtypes)

Data Types:

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [142]:
print("Missing Values:")
display(spaceship.isnull().sum())

Missing Values:

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

**Deal with Nulls**

In [143]:
# handle missing values
spaceship["HomePlanet"] = spaceship["HomePlanet"].fillna("Unknown") # fill missing values with "Unknown"
spaceship["CryoSleep"] = spaceship["CryoSleep"].fillna(False)
spaceship["Destination"] = spaceship["Destination"].fillna("Unknown") # fill missing values with "Unknown"
spaceship["Age"] = spaceship["Age"].fillna(spaceship["Age"].median()) # fill missing values with median before converting to int
spaceship["RoomService"] = spaceship["RoomService"].fillna(0) # fill missing values with 0
spaceship["FoodCourt"] = spaceship["FoodCourt"].fillna(0) # fill missing values with 0
spaceship["ShoppingMall"] = spaceship["ShoppingMall"].fillna(0) # fill missing values with 0
spaceship["Spa"] = spaceship["Spa"].fillna(0) # fill missing values with 0
spaceship["VRDeck"] = spaceship["VRDeck"].fillna(0) # fill missing values with 0
spaceship["Cabin"] = spaceship["Cabin"].fillna("Unknown") # fill missing values with "Unknown"

C:\Users\sboub\AppData\Local\Temp\ipykernel_23660\3947118155.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  spaceship["CryoSleep"] = spaceship["CryoSleep"].fillna(False)

**Deal with Duplicates**

In [144]:
# remove duplicates
spaceship = spaceship.drop_duplicates()

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [145]:
print("unique values in 'Cabin' column before splitting:", spaceship['Cabin'].unique())
# split the 'Cabin' column into A, B, C, D, E, F, G, T...Z
spaceship['Cabin'] = spaceship['Cabin'].str[0]
# check the unique values again
print("unique values in 'Cabin' column after splitting:", spaceship['Cabin'].unique())

unique values in 'Cabin' column before splitting: ['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
unique values in 'Cabin' column after splitting: ['B' 'F' 'A' 'G' 'U' 'E' 'D' 'C' 'T']

- Drop PassengerId and Name

In [146]:
# drop PassengerId and Name columns since they are not useful for modeling
spaceship.drop(["PassengerId", "Name"], axis=1, inplace=True)

- For non-numerical columns, do dummies.

In [147]:
#your code here

**Convert Data Types**

In [148]:
spaceship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8693 non-null   object
 1   CryoSleep     8693 non-null   bool
 2   Cabin         8693 non-null   object
 3   Destination   8693 non-null   object
 4   Age           8693 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8693 non-null   float64
 7   FoodCourt     8693 non-null   float64
 8   ShoppingMall  8693 non-null   float64
 9   Spa           8693 non-null   float64
 10  VRDeck        8693 non-null   float64
 11  Transported   8693 non-null   bool
dtypes: bool(2), float64(6), object(4)
memory usage: 696.2+ KB

In [149]:
# convert Age to integer type
spaceship["Age"] = spaceship["Age"].astype(int)

# convert VIP to boolean type
spaceship["VIP"] = spaceship["VIP"].astype(bool)

# convert booleans to integers (True=1, False=0) for modeling
for col in spaceship.columns:
    if spaceship[col].dtype == 'bool':
        spaceship[col] = spaceship[col].astype(int)

**Perform Train Test Split**
- split spaceship dataset into train and test sets (stratify by target variable to maintain class distribution)

**Define target (y)**

In [150]:
# define target variable
y = spaceship["Transported"]

**Define features (X)**

In [151]:
# define features: 
X = spaceship.drop(["Transported"], axis=1)
print(f"Shape of data after dropping 'Transported', 'PassengerId', 'Name': {X.shape}")
display(X.head())

Shape of data after dropping 'Transported', 'PassengerId', 'Name': (8693, 11)

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Europa,0,B,TRAPPIST-1e,39,0,0.0,0.0,0.0,0.0,0.0
1,Earth,0,F,TRAPPIST-1e,24,0,109.0,9.0,25.0,549.0,44.0
2,Europa,0,A,TRAPPIST-1e,58,1,43.0,3576.0,0.0,6715.0,49.0
3,Europa,0,A,TRAPPIST-1e,33,0,0.0,1283.0,371.0,3329.0,193.0
4,Earth,0,F,TRAPPIST-1e,16,0,303.0,70.0,151.0,565.0,2.0

**SPLIT**

In [152]:
# define train-test split sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

#display the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (6954, 11)
X_test shape: (1739, 11)
y_train shape: (6954,)
y_test shape: (1739,)

**Feature Engineering**

1. Identity Categorical vs Numerical Features

In [153]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Boolean columns (already 0/1)
bool_cols = ["CryoSleep", "VIP"]

# Categorical columns (more than 2 categories)
cat_cols = ["HomePlanet", "Cabin", "Destination"]

# Numerical columns
num_cols = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]

2. one hot encode categorical features (not boolean)

In [154]:
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

X_train_cat = pd.DataFrame(
    ohe.fit_transform(X_train[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_train.index
)

X_test_cat = pd.DataFrame(
    ohe.transform(X_test[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_test.index
)

3. Scale Numerical Columns

In [155]:
scaler = StandardScaler()

X_train_num = pd.DataFrame(
    scaler.fit_transform(X_train[num_cols]),
    columns=num_cols,
    index=X_train.index
)

X_test_num = pd.DataFrame(
    scaler.transform(X_test[num_cols]),
    columns=num_cols,
    index=X_test.index
)

4. Convert Booleans to int (True=1 , False=0)

In [156]:
# Boolean columns (already 0/1)
X_train_bool = X_train[bool_cols]
X_test_bool = X_test[bool_cols]

5. Combine & Save Train Test sets CSVs

In [157]:
# Combine all features
X_train = pd.concat([X_train_num, X_train_bool, X_train_cat], axis=1)
X_test = pd.concat([X_test_num, X_test_bool, X_test_cat], axis=1)

# display the shapes of the resulting sets
print("X_train shape after encoding and scaling:", X_train.shape)
display(X_train.head())
print("X_test shape after encoding and scaling:", X_test.shape)
display(X_test.head())

print("y_train shape:", y_train.shape)
display(y_train.head())
print("y_test shape:", y_test.shape)
display(y_test.head())

# ---- Save preprocessed data to CSV files ----
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

X_train shape after encoding and scaling: (6954, 25)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,CryoSleep,VIP,HomePlanet_Earth,HomePlanet_Europa,...,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_U,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Destination_Unknown
3600,-1.996149,-0.33634,-0.279076,-0.305732,-0.267311,-0.264632,0,0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1262,-0.811703,-0.33634,-0.279076,-0.305732,-0.267311,-0.264632,1,0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8612,0.442416,-0.33634,-0.279076,-0.305732,-0.267311,-0.264632,0,0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
5075,-0.184643,-0.33634,-0.279076,-0.305732,-0.267311,-0.264632,1,0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4758,-1.090396,-0.33634,-0.279076,-0.195161,-0.266427,4.423937,0,0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

X_test shape after encoding and scaling: (1739, 25)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,CryoSleep,VIP,HomePlanet_Earth,HomePlanet_Europa,...,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_U,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Destination_Unknown
3586,0.372743,-0.336340,-0.279076,-0.305732,-0.267311,-0.264632,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7173,-1.717456,-0.336340,-0.279076,-0.305732,-0.267311,-0.264632,1,0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8559,-0.254317,0.275593,-0.258898,-0.279932,0.828625,-0.255523,0,0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6528,-1.160070,-0.336340,-0.279076,-0.305732,-0.267311,-0.264632,0,1,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7934,2.602289,-0.336340,0.873578,-0.303889,1.389418,-0.223640,0,1,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

y_train shape: (6954,)

3600    1
1262    1
8612    0
5075    1
4758    0
Name: Transported, dtype: int64

y_test shape: (1739,)

3586    1
7173    0
8559    0
6528    1
7934    0
Name: Transported, dtype: int64

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [158]:
from sklearn.neighbors import KNeighborsClassifier
# --- classification problem since target variable is binary (True/False) ---

# define KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model to the training data
knn.fit(X_train, y_train)

KNeighborsClassifier()

- Evaluate your model's performance. Comment it

Test Accuracy: 0.771

Train Accuracy: 0.829

Cross-validation Mean Accuracy: 0.767

Test ROC AUC: 0.848

Train ROC AUC: 0.917

PR AUC: 0.841

Confusion Matrix:
[[662, 201],
[197, 679]]

In [159]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    average_precision_score,
    roc_auc_score,
    confusion_matrix
)
# evaluate the KNN model on the test set
# metrics to evaluate: accuracy, Classification Report, Precision-Recall AUC, ROC AUC, Confusion Matrix


# Predictions
y_pred = knn.predict(X_test)
y_proba = knn.predict_proba(X_test)[:, 1]

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("KNN Accuracy:", accuracy)

# Classification Report
print("KNN Classification Report:\n")
print(classification_report(y_test, y_pred))

# Precision-Recall AUC
pr_auc = average_precision_score(y_test, y_proba)
print("KNN PR AUC:", pr_auc)

# ROC AUC
roc_auc = roc_auc_score(y_test, y_proba)
print("KNN ROC AUC:", roc_auc)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("KNN Confusion Matrix:\n", conf_matrix)

KNN Accuracy: 0.7711328349626222
KNN Classification Report:

              precision    recall  f1-score   support

           0       0.77      0.77      0.77       863
           1       0.77      0.78      0.77       876

    accuracy                           0.77      1739
   macro avg       0.77      0.77      0.77      1739
weighted avg       0.77      0.77      0.77      1739

KNN PR AUC: 0.8407022409555126
KNN ROC AUC: 0.8476516823018355
KNN Confusion Matrix:
 [[662 201]
 [197 679]]

**Check Model is not overfitting or underfitting**

- **FITTING CORRECTLY:** Small difference → model generalizes well.
- **OVERFITTING:** Large gap → model memorized training data. Rule of Thumb → If: Train Accuracy − Test Accuracy > 5–7% probably overfitting.
- **UNDERFITTING:** Both low → model too simple.

**Method 1 for checking: Compare Train Accuracy vs Test Accuracy**

In [160]:
# Train accuracy
train_acc = knn.score(X_train, y_train)

# Test accuracy
test_acc = knn.score(X_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy :", test_acc)

Train Accuracy: 0.8291630716134599
Test Accuracy : 0.7711328349626222

**Method 2 for checking : Compare ROC AUC Train vs Test (More reliable than accuracy)**

In [161]:
from sklearn.metrics import roc_auc_score

train_roc = roc_auc_score(y_train, knn.predict_proba(X_train)[:,1])
test_roc  = roc_auc_score(y_test, knn.predict_proba(X_test)[:,1])

print("Train ROC AUC:", train_roc)
print("Test ROC AUC :", test_roc)

Train ROC AUC: 0.9167701637799424
Test ROC AUC : 0.8476516823018355

**Higher k → smoother decision boundary → less overfitting.**

**CROSS VALIDATION**

- If CV score ≈ test score → good.
- If CV score much lower than train → overfitting.

In [162]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(knn, X_train, y_train, cv=5)
print("Cross-validation mean accuracy:", scores.mean())

Cross-validation mean accuracy: 0.7668954067515218

#### Model Evaluation
- Test Accuracy: 0.771 
- Cross-val Accuracy: 0.767
- ROC AUC (Test): 0.848
- PR AUC: 0.841

🔎 Overfitting Check
- Train Accuracy: 0.829
- Test Accuracy: 0.771
- Moderate gap (~6%) → Mild overfitting, acceptable

⚖ Class Performance
- Precision, Recall, F1 all ~0.77 for both classes → Balanced predictions, no class bias